(library
 (name kernel)
 (synopsis "The Rocq Kernel")
 (public_name rocq-runtime.kernel)
 (wrapped false)
 (modules_without_implementation values declarations entries)
 (modules (:standard \ genOpcodeFiles uint63_31 uint63_63 float64_31 float64_63))
 (libraries boot lib coqrun dynlink))

; used by dune coq mode
(deprecated_library_name
 (old_public_name coq-core.kernel)
 (new_public_name rocq-runtime.kernel))

(executable
  (name genOpcodeFiles)
  (modules genOpcodeFiles))

(rule
 (targets vmopcodes.ml)
 (action (with-stdout-to %{targets} (run ./genOpcodeFiles.exe copml))))

(rule
 (targets vmopcodes.mli)
 (action (with-stdout-to %{targets} (run ./genOpcodeFiles.exe copmli))))

(rule
 (targets uint63.ml)
 (deps (:gen-file uint63_%{ocaml-config:int_size}.ml))
 (action (copy# %{gen-file} %{targets})))

(rule
 (targets float64.ml)
 (deps (:gen-file float64_%{ocaml-config:int_size}.ml))
 (action (copy# %{gen-file} %{targets})))

(rule
 (target cClosure.ml)
 (deps cClosure.ml.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 0" %{deps}))))

(rule
 (target cClosure.mli)
 (deps cClosure.mli.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 0" %{deps}))))

(rule
 (target cClosureProfile.ml)
 (deps cClosure.ml.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 1" %{deps}))))

(rule
 (target cClosureProfile.mli)
 (deps cClosure.mli.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 1" %{deps}))))

(rule
 (target conversion.ml)
 (deps conversion.ml.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 0" %{deps}))))

(rule
 (target conversion.mli)
 (deps conversion.mli.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 0" %{deps}))))

(rule
 (target conversionProfile.ml)
 (deps conversion.ml.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 1" %{deps}))))

(rule
 (target conversionProfile.mli)
 (deps conversion.mli.cppo)
 (action
  (with-stdout-to %{target}
   (run %{bin:cppo} -n -D "PROFILED 1" %{deps}))))

(documentation
 (package rocq-runtime))

; In dev profile, we check the kernel against a more strict set of
; warnings.
(env
 (dev (flags :standard -w @a-4-40-42-44-50)))
